### ISSUE TITLE
Create a new project - Secured Spring Boot Tomcat Quickstart - fails

### ISSUE THREAD

**Issue by ldimaggi** [snowdrop/spring-boot-http-secured-booster#19]
See details here:
https://github.com/fabric8-ui/fabric8-ui/issues/1660

**Comment by rdruss** [comment]
Related to an existing issue adopting the Fabric8 Jenkins Pipeline Library:
https://github.com/openshiftio/appdev-planning/issues/35

**Comment by metacosm** [comment]
Outdated.
